apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 192.168.1.40:5000/test
  newTag: 87c7c6197c1175f60f1c0b9ef567b883651a596f
