apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: demo
        env:
        - name: ENVIRONMENT
          value: prod
