apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 192.168.1.40:5000/test
  newTag: a8b40c555b1e08a36901cd9090ced95b8ef28e54
resources:
- ../base
