apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: 192.168.1.40:5000/test:62ad884a4968117d9ac7b14f0305c578a7723486
        name: demo
        ports:
        - containerPort: 8080
